---
- name: Backup devices from UKTME lab
  hosts: all
  gather_facts: no
  connection: local

  tasks:
          - name: SYS | Getting ansible date/time
            setup:
              filter: "ansible_date_time"
              gather_subset: "!all"
            run_once: true

          - name: SYS | Store DTG as fact
            set_fact:
              DTG: "{{ ansible_date_time.date }}"

          - name: SYS | Define provider
            set_fact:
                  logins:
                          host: "{{ inventory_hostname }}"
                          username: "{{user}}"
                          password: "{{pass}}"

          - name: IOS | Show Hostname
            ios_command:
              provider: "{{logins}}"
              commands:
                - ter len 0
                - show run | inc hostname
            register: hostname

          - name: SYS | Getting name part of split
            set_fact:
              host: "{{hostname.stdout[1].split()[1]}}"

          - name: IOS | backup to ftp
            register: backup
            ios_command:
                  provider: "{{logins}}"
                  commands:
                    - 'conf t'
                    - 'file prompt quiet'
                    - 'end'
                    - 'copy running-config flash:running-config.txt'
                    - 'copy flash:running-config.txt ftp://10.52.248.78/config_backups/{{DTG}}-{{host}}.backup'

          - name: Messaging teams
            cisco_spark:
              recipient_type: toPersonEmail
              recipient_id: "{{teams_email}}"
              message_type: text
              personal_token: "ZmYwMjRmYjEtNWM4ZC00NGQ0LTk3NmMtNTZhZDE1ZmM0OTc4ZDEzMTk4OWUtMDhj_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
              message: "The list of devices that has been backed up" 
            run_once: yes

          - name: Messaging on Webex Teams
            cisco_spark:
              recipient_type: toPersonEmail
              recipient_id: "{{teams_email}}"
              message_type: text
              personal_token: "ZmYwMjRmYjEtNWM4ZC00NGQ0LTk3NmMtNTZhZDE1ZmM0OTc4ZDEzMTk4OWUtMDhj_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
              message: "{{host}}" 
